name: double_back_to_close_app_example
description: Demonstrates how to use the double_back_to_close_app plugin.
publish_to: 'none'

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  double_back_to_close_app:
    path: ../
